// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnwbtmpafpfrrefhqzii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxud2J0bXBhZnBmcnJlZmhxemlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTU5ODMsImV4cCI6MjA1MzczMTk4M30.mYkJ46kLGRS68UBEw14hUtiXL7LuFO9Uo3k74sj7XxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);